#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:mem:voting_system
    username: sa
    password:
  #    tcp: jdbc:h2:tcp://localhost:9092/mem:voting
  h2:
    console:
      enabled: true

  #Jackson Serialization Issue Resolver
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
  # https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
    cache-names: users, restaurants
    caffeine:
      spec: maximumSize=1,expireAfterAccess=60s

logging:
  level:
    root: WARN
    com.lavgorush.graduation_project.voting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG


server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

